version: '3'
services:
  ui:
    image: nginx
    ports:
      - 80:80  
  back:
    image: mongo-express
    ports:
      - 8081:8081
  mongo:
    image: mongo
    ports:
      - 27017:27010
    volumes:
      - data_db:/data/db
volumes:
  data_db: